#!/usr/bin/env bash
# Generates ${WATO_WORLD_DIR}/modules/.env from watod-config.sh values + host
# state (UID/GID, git branch).  Mirrors wato_monorepo/watod_scripts/watod-setup-env.sh.

set -euo pipefail

: "${WATO_WORLD_DIR:?WATO_WORLD_DIR must be set by the watod entrypoint}"
: "${REGISTRY:=ghcr.io/watonomous/wato_world}"
: "${GPU_AVAILABLE:=false}"
: "${CLAUDE_CODE:=false}"
: "${ARTIFACT_ROOT_URI:=file:///data/artifacts}"
: "${BAG_ROOT:=/data/bags}"
: "${MODELS_ROOT:=/data/models}"

OUT="${WATO_WORLD_DIR}/modules/.env"

# --- TAG: git branch slug; "untracked" if not a git repo. -------------------
if git -C "${WATO_WORLD_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    BRANCH="$(git -C "${WATO_WORLD_DIR}" rev-parse --abbrev-ref HEAD)"
    TAG="${BRANCH//\//-}"
else
    TAG="untracked"
fi

# --- Host user mapping (for the develop target). ---------------------------
SETUID="$(id -u)"
SETGID="$(id -g)"
USERNAME="${USER:-wato}"

# --- Component image names. -----------------------------------------------
INGEST_IMAGE="${REGISTRY}/ingest"
PERCEPTION_2D_IMAGE="${REGISTRY}/perception_2d"
LIDAR_PREPROCESSING_IMAGE="${REGISTRY}/lidar_preprocessing"
PROPOSAL_GENERATION_IMAGE="${REGISTRY}/proposal_generation"
TRACKING_IMAGE="${REGISTRY}/tracking"
LABEL_REFINEMENT_IMAGE="${REGISTRY}/label_refinement"
OPEN_VOCAB_DISCOVERY_IMAGE="${REGISTRY}/open_vocab_discovery"
STUDENT_TRAINING_IMAGE="${REGISTRY}/student_training"
BASE_CUDA_IMAGE="${REGISTRY}/base"
BASE_CPU_IMAGE="${REGISTRY}/base"

mkdir -p "$(dirname "${OUT}")"
cat >"${OUT}" <<EOF
# Generated by watod-setup-env.sh — do not edit by hand.
WATO_WORLD_DIR=${WATO_WORLD_DIR}
TAG=${TAG}

USERNAME=${USERNAME}
SETUID=${SETUID}
SETGID=${SETGID}
CLAUDE_CODE=${CLAUDE_CODE}
GPU_AVAILABLE=${GPU_AVAILABLE}

REGISTRY=${REGISTRY}
INGEST_IMAGE=${INGEST_IMAGE}
PERCEPTION_2D_IMAGE=${PERCEPTION_2D_IMAGE}
LIDAR_PREPROCESSING_IMAGE=${LIDAR_PREPROCESSING_IMAGE}
PROPOSAL_GENERATION_IMAGE=${PROPOSAL_GENERATION_IMAGE}
TRACKING_IMAGE=${TRACKING_IMAGE}
LABEL_REFINEMENT_IMAGE=${LABEL_REFINEMENT_IMAGE}
OPEN_VOCAB_DISCOVERY_IMAGE=${OPEN_VOCAB_DISCOVERY_IMAGE}
STUDENT_TRAINING_IMAGE=${STUDENT_TRAINING_IMAGE}
BASE_CUDA_IMAGE=${BASE_CUDA_IMAGE}
BASE_CPU_IMAGE=${BASE_CPU_IMAGE}

ARTIFACT_ROOT_URI=${ARTIFACT_ROOT_URI}
BAG_ROOT=${BAG_ROOT}
MODELS_ROOT=${MODELS_ROOT}
EOF

echo "Wrote ${OUT}"
