---
name: Build Wato World Base Images

on:
  push:
    branches:
      - main
    paths:
      - "docker/base/**"
      - ".github/include/base_image_config.json"
      - ".github/templates/docker_context/**"
      - ".github/workflows/build_base_images.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    outputs:
      registry: ${{ steps.docker-context.outputs.registry }}
      repository: ${{ steps.docker-context.outputs.repository }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Docker Context
        id: docker-context
        uses: "./.github/templates/docker_context"

  base-matrix-prep:
    name: Prepare Base Image Matrix JSON
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prep.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Image Matrix
        id: prep
        run: |
          matrix="$(jq -c . .github/include/base_image_config.json)"
          echo "Base Image Matrix: ${matrix}"
          echo "matrix=${matrix}" >> "${GITHUB_OUTPUT}"
        shell: bash

  build:
    name: Build Base Images
    runs-on: ubuntu-latest
    needs: [setup-environment, base-matrix-prep]

    env:
      DOCKER_REGISTRY: ${{ needs.setup-environment.outputs.registry }}
      DOCKER_REPOSITORY: ${{ needs.setup-environment.outputs.repository }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.base-matrix-prep.outputs.matrix) }}

    concurrency:
      group: ${{ matrix.tag }}-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Construct Registry URL
        id: construct-registry-url
        run: |
          echo "url=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/base:${{ matrix.tag }}" \
            >> "${GITHUB_OUTPUT}"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.construct-registry-url.outputs.url }}
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            GENERIC_IMAGE=${{ matrix.external_image }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          provenance: false
          cache-from: type=gha,scope=base-${{ matrix.flavor }}
          cache-to: type=gha,scope=base-${{ matrix.flavor }},mode=max
